name: "ğŸ“‹ Release"

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+[0-9A-Za-z]?'

env:
  REGISTRY: "153151009581.dkr.ecr.ap-southeast-2.amazonaws.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Git clone the repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.REGISTRY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REGISTRY_AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-southeast-2

      - name: ğŸ” Log in to Registries
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${REGISTRY}

      - name: ğŸ“¦ Build
        run: |
          docker build -t ${{ env.REGISTRY }}/skpr/lambda-eks-event-cloudwatch:${{ github.ref_name }} .

      - name: â˜ï¸ Push
        run: |
          docker push ${{ env.REGISTRY }}/skpr/lambda-eks-event-cloudwatch:${{ github.ref_name }}
